### PR TITLE
Source callsign

### PR DESCRIPTION
**Pull request by MichaelDBrown**
Provide ability to log and expose in api the source callsign from transmissions.

### CODE REVIEW

**Review by nonoo — CHANGES_REQUESTED** [review]
Can you please fix these?

Please leave 1 byte for the closing zero for src_callsign.

Please don't use the & address operator on char arrays to conform with the coding style.

It's advisable to use a predefined length array for lastheard_add()'s src_callsign parameter.

Please handle the case of NULL passed to lastheard_add (it will cause a segfault now).

You can't printf an uint32_t casted to a char pointer (packet.c:290). I'm sure the compiler throws a warning about this. packet.c:303 and 309 are problematic also. 

packet.c:395 starts with an unneeded space before (char *).

**Comment by MichaelDBrown** [comment]
I want to make sure I understand your request:

1. Please leave 1 byte for the closing zero for src_callsign. - So you're asking that the length be one greater than the maximum callsign size for the lastheard src_callsign array??

2. Please don't use the & address operator on char arrays to conform with the coding style.  - I don't understand. Instead of using the & to get the address, you want me to do what to get the address?

3. It's advisable to use a predefined length array for lastheard_add()'s src_callsign parameter. - Instead of using the defined constant, you want me to just put the integer for the length?

4. Please handle the case of NULL passed to lastheard_add (it will cause a segfault now). - Yep, understood, I missed this. 

5. You can't printf an uint32_t casted to a char pointer (packet.c:290). I'm sure the compiler throws a warning about this. packet.c:303 and 309 are problematic also. - I'm not seeing the compiler warning, and I do not believe they are uint32_t. They are uint8_t according to srf-ip-conn-packet.h.

6. packet.c:395 starts with an unneeded space before (char *). - Understood.

**Comment by nonoo** [comment]
1. Yes
2. As I wrote, address operator is not needed
3. Use an array definition like a[LENGTH]
5.DMR src_id is a 24 bit value stored in a 3 byte array

**Comment by w7xm-zz** [comment]
any more updates on this update?

**Comment by MichaelDBrown** [comment]
I didn’t have the skills to complete the fixes for modes other than Fusion. For Fusion the changes work without issue. For other modes, the changes need someone with better C skills.

**Pull request closed without merging**
